### ISSUE TITLE
DOC: add instructions for mac os

### ISSUE THREAD

**Issue by urfv** [automateyournetwork/Document_Buddy#9]
Hey! I've tried composing the docker container but i get this error:
`Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]`

I'm on mac, and ollama itself runs flawlessly. Can you please add a workaround to the documentation? I'm new to this so I would really appreciate any help. Thank you! Really excited to try this out

**Comment by automateyournetwork** [comment]
You should be able to use Docker on Mac

**Comment by Avi-141** [comment]
Hi John.
Couple of things
The docker compose is trying to pull an image which i think is private, due to which i get this warning

 ! document_buddy Warning   pull access denied for johncapobianco/document_buddy, repository does not exist or may require 'docker login': denied: requested acc...                         5.0s 
 
 
Im new to this, how can i fix this?

**Comment by Avi-141** [comment]
> You should be able to use Docker on Mac

We will need to remove nvidia gpu configurations from docker compose @urfv

**Comment by automateyournetwork** [comment]
It should build the docker image locally from the Docker file inside the
Docker folder

I am not a Mac user but for Windows there is Docker Desktop and you just
need to say docker compose up to get it working

My apologies I am sorry you are having troubles
